serverAddr = "f.webrtc.win"
serverPort = 7000
auth.method = "token"
auth.token = "jdog"
loginFailExit = false
log.disablePrintColor = true

[[proxies]]
name = "ssh-16000"
type = "tcp"
localIp = "127.0.0.1"
localPort = 22
remotePort = 16000